<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li>Liste des utilisateurs</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerUsers">
    <?php if(!in_array("22", $prv) && !in_array("23", $prv) && !in_array("24", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php elseif(isset($page)): ?>
        <h3><i class="fa fa-list-ul"></i>Liste des utilisateurs</h3>
        <?php if(in_array("23", $prv)) { ?>
            <h3><a href="/importgames/backoff/ajoutuser"><i class="fa fa-plus"></i>Ajouter un utilisateur</a></h3>
        <?php } ?>
        <form class="formLines" method="POST">
            <label for="lignesUser">Afficher par : </label>
            <select id="lignesUser" name="lignesUser">
                <?php if($nbrUsers[0] <= 100) { ?>
                <option value="5">5</option>
                <?php }
                if($nbrUsers[0] <= 250) { ?>
                <option value="10">10</option>
                <?php } ?>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                <?php if($nbrUsers[0] > 100) { ?>
                <option value="250">250</option>
                <?php }
                if($nbrUsers[0] > 250) { ?>
                <option value="500">500</option>
                <?php } ?>
            </select>
        </form>
        <div>Résultats <?= $resultDebut ?> à <?= htmlspecialchars($resultFin) ?> sur <?= htmlspecialchars($nbrUsers[0]) ?></div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
                <?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/users-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/users-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($next)): ?>
                    <div class="pageSuiv"><a href="/importgames/backoff/users-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/users-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                <?php endif;
                // Si le nombre de pages de pages est supérieur à 1 (voir utilisateurs.php ligne 132),
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php // on affiche le nombre de pages avec leurs liens
                    for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/users-page-<?= $i ?>" id="lienPageTop<?= $i ?>"><?= $i ?></a></span>
                    <?php endfor;
                } ?>
            </div>
        <?php } ?>
        <div class="tableScroll">
            <table>
                <thead>
                    <tr>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserId">
                                    <i id="arrowDownUserId" class="fa fa-long-arrow-down"></i><i id="arrowUpUserId" class="fa fa-long-arrow-up"></i>
                                    <div>Id</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUsern">
                                    <i id="arrDwnUsrUsern" class="fa fa-long-arrow-down"></i><i id="arrUpUsrUsern" class="fa fa-long-arrow-up"></i>
                                    <div>Nom d'utilisateur</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserMail">
                                    <i id="arrDwnUsrMail" class="fa fa-long-arrow-down"></i><i id="arrUpUsrMail" class="fa fa-long-arrow-up"></i>
                                    <div>E-mail</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserPass">
                                    <i id="arrDwnUsrPass" class="fa fa-long-arrow-down"></i><i id="arrUpUsrPass" class="fa fa-long-arrow-up"></i>
                                    <div>Mot de passe</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserNom">
                                    <i id="arrDwnUsrNom" class="fa fa-long-arrow-down"></i><i id="arrUpUsrNom" class="fa fa-long-arrow-up"></i>
                                    <div>Nom</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserPrenom">
                                    <i id="arrDwnUsrPrenom" class="fa fa-long-arrow-down"></i><i id="arrUpUsrPrenom" class="fa fa-long-arrow-up"></i>
                                    <div>Prénom</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserAdresse">
                                    <i id="arrDwnUsrAdress" class="fa fa-long-arrow-down"></i><i id="arrUpUsrAdress" class="fa fa-long-arrow-up"></i>
                                    <div>Adresse</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserZip">
                                    <i id="arrDwnUsrZip" class="fa fa-long-arrow-down"></i><i id="arrUpUsrZip" class="fa fa-long-arrow-up"></i>
                                    <div>Code postal</div>
                                </button>
                            </form>
                        </th>
                        <?php if(in_array("24", $prv)) { ?>
                            <th>Options</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($users as $user): ?>
                    <tr>
                        <td><?= htmlspecialchars($user["id"]) ?></td>
                        <td>
                            <?php if($user["username"]): echo htmlspecialchars($user["username"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["email"]): echo htmlspecialchars($user["email"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td title="<?= htmlspecialchars($user["password"]) ?>">
                            <?php if($user["password"]): echo htmlspecialchars(couperTexte($user["password"])); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["nom"]): echo htmlspecialchars($user["nom"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["prenom"]): echo htmlspecialchars($user["prenom"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["adresse"]): echo htmlspecialchars($user["adresse"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["code_postal"]): echo htmlspecialchars($user["code_postal"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <?php if(in_array("24", $prv)) { ?>
                            <td>
                                <a href="/importgames/backoff/modifuser-<?= htmlspecialchars($user["id"]) ?>" class="btnModif"><?php if($user["username"]): ?><i class="fa fa-pencil-square-o"></i>Modifier<?php else: ?><i class="fa fa-exchange"></i>Remplacer<?php endif; ?></a>
                                <?php if($user["username"]) { ?>
                                    <form class="formReset" method="POST">
                                        <button type="submit" id="resetUser<?= htmlspecialchars($user["id"]) ?>" class="btnReset" name="resetUser" value="<?= htmlspecialchars($user["id"]) ?>"><i class="fa fa-trash-o"></i>Supprimer</button>
                                        <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
                                        <input type="hidden" name="formToken" value="<?= $token ?>" />
                                    </form>
                                <?php } ?>
                            </td>
                        <?php } ?>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <table>
                <thead>
                    <tr>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserId">
                                    <span>Id</span>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserVille">
                                    <i id="arrDwnUsrVille" class="fa fa-long-arrow-down"></i><i id="arrUpUsrVille" class="fa fa-long-arrow-up"></i>
                                    <div>Ville</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserPays">
                                    <i id="arrDwnUsrPays" class="fa fa-long-arrow-down"></i><i id="arrUpUsrPays" class="fa fa-long-arrow-up"></i>
                                    <div>Pays</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserTel">
                                    <i id="arrDwnUsrTel" class="fa fa-long-arrow-down"></i><i id="arrUpUsrTel" class="fa fa-long-arrow-up"></i>
                                    <div>Téléphone</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserDateReg">
                                    <i id="arrDwnUsrReg" class="fa fa-long-arrow-down"></i><i id="arrUpUsrReg" class="fa fa-long-arrow-up"></i>
                                    <div>Date d'inscription</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserToken">
                                    <i id="arrDwnUsrTk" class="fa fa-long-arrow-down"></i><i id="arrUpUsrTk" class="fa fa-long-arrow-up"></i>
                                    <div>Token</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserConfCte">
                                    <i id="arrDwnUsrConf" class="fa fa-long-arrow-down"></i><i id="arrUpUsrConf" class="fa fa-long-arrow-up"></i>
                                    <div>Date de confirmation du compte</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserTokStayco">
                                    <i id="arrDwnUsrTkStayc" class="fa fa-long-arrow-down"></i><i id="arrUpUsrTkStayc" class="fa fa-long-arrow-up"></i>
                                    <div>Token "rester connecté"</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserNewPass">
                                    <i id="arrDwnUsrNewPass" class="fa fa-long-arrow-down"></i><i id="arrUpUsrNewPass" class="fa fa-long-arrow-up"></i>
                                    <div>Demande nouveau mot de passe</div>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triUserDateUnsub">
                                    <i id="arrDwnUsrUnsub" class="fa fa-long-arrow-down"></i><i id="arrUpUsrUnsub" class="fa fa-long-arrow-up"></i>
                                    <div>Date de désinscription</div>
                                    </button>
                            </form>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($users as $user): ?>
                    <tr>
                        <td><?= htmlspecialchars($user["id"]) ?></td>
                        <td>
                            <?php if($user["ville"]): echo htmlspecialchars($user["ville"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["pays"]): echo htmlspecialchars($user["pays"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["tel"]): echo htmlspecialchars($user["tel"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["date_reg"]): echo htmlspecialchars(date("d/m/Y", strtotime($user["date_reg"]))); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td title="<?= htmlspecialchars($user["token"]) ?>">
                            <?php if($user["token"]): echo htmlspecialchars(couperTexte($user["token"])); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["conf_account"]): echo htmlspecialchars(date("d/m/Y H:i", strtotime($user["conf_account"]))); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td title="<?= htmlspecialchars($user["token_stayco"]) ?>">
                            <?php if($user["token_stayco"]): echo htmlspecialchars(couperTexte($user["token_stayco"])); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if(isset($user["new_pass"])): echo htmlspecialchars($user["new_pass"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($user["date_unsub"]): echo htmlspecialchars(date("d/m/Y H:i", strtotime($user["date_unsub"]))); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
                <?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/users-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/users-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($next)): ?>
                    <div class="pageSuiv"><a href="/importgames/backoff/users-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/users-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                <?php endif;
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/users-page-<?= $i ?>" id="lienPage<?= $i ?>"><?= $i ?></a></span>
                    <?php endfor;
                } ?>
            </div>
        <?php }
    endif; ?>
    <div class="backLink"><a href="/importgames/backoff/tableau-de-bord"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Accueil</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>