<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li><a href="/importgames/backoff/slid-page-1">Liste des slides</a></li>
        <li class="titreFil">Ajouter un slide</li>
        <li class="titreFil300" title="Ajouter un slide">...</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerAjout">
    <?php if(!in_array("5", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php else: ?>
    	<h3><i class="fa fa-plus"></i>Ajouter un slide</h3>
        <form enctype="multipart/form-data" method="POST">
            <div>
                <label for="titre">Titre :</label>
                <input type="text" id="titre" name="titre" value="<?php if(isset($_POST["titre"])) echo htmlspecialchars($_POST["titre"]); ?>" required />
                <?php if(isset($emptyTitre)): ?>
                    <p>Le <em>titre</em> ne peut pas être vide.</p>
                <?php elseif(isset($invalidTitre)): ?>
                    <p>Le <em>titre</em> ne doit comporter aucun chiffres ni caractères spéciaux et ne pas dépasser 16 caractères.</p>
                <?php endif; ?>
            </div>
            <div>
                <label for="leg">Légende :</label>
                <input type="text" id="leg" name="leg" value="<?php if(isset($_POST["leg"])) echo htmlspecialchars($_POST["leg"]); ?>" required />
                <?php if(isset($emptyLeg)) { ?>
                    <p>La <em>légende</em> ne peut pas être vide.</p>
                <?php } ?>
            </div>
            <div>
                <input type="hidden" name="MAX_FILE_SIZE" value="5000000" />
                <label for="img">Image :</label>
                <input type="file" id="img" name="img" accept=".gif, .jpeg, .jpg, .png, .svg" required />
                <?php if(isset($emptyImg)): ?>
                    <p>Le fichier <em>image</em> ne peut pas être vide ou dépasser la taille de 5000 Ko.</p>
                <?php elseif(isset($errorImg)): ?>
                    <p>Une erreur s'est produite lors de la vérification du fichier.</p>
                <?php endif; ?>
            </div>
            <input type="submit" class="btn" name="ajoutSlid" value="Valider" />
            <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
            <input type="hidden" name="formToken" value="<?= $token ?>" />
            <?php if(isset($verifError)): ?>
                <div class="msg"><p>Erreur de vérification.</p></div>
            <?php elseif(isset($refError)): ?>
                <div class="msg"><p>La requête ne provient pas du formulaire.</p></div>
            <?php endif; ?>
        </form>
    <?php endif; ?>
    <div class="backLink"><a href="/importgames/backoff/slid-page-1"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Retour</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>