<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li>Liste des catégories</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerCats">
    <?php if(!in_array("1", $prv) && !in_array("2", $prv) && !in_array("3", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php elseif(isset($page)): ?>
    	<h3><i class="fa fa-list-ul"></i>Liste des catégories</h3>
        <?php if(in_array("2", $prv)) { ?>
            <h3><a href="/importgames/backoff/ajoutcat"><i class="fa fa-plus"></i>Ajouter une catégorie</a></h3>
        <?php } ?>
        <form class="formLines" method="POST">
            <label for="lignesCat">Afficher par : </label>
            <select id="lignesCat" name="lignesCat">
                <?php if($nbrCats[0] <= 100) { ?>
                <option value="5">5</option>
                <?php }
                if($nbrCats[0] <= 250) { ?>
                <option value="10">10</option>
                <?php } ?>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                <?php if($nbrCats[0] > 100) { ?>
                <option value="250">250</option>
                <?php }
                if($nbrCats[0] > 250) { ?>
                <option value="500">500</option>
                <?php } ?>
            </select>
        </form>
        <div>Résultats <?= $resultDebut ?> à <?= htmlspecialchars($resultFin) ?> sur <?= htmlspecialchars($nbrCats[0]) ?></div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
                <?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/cats-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/cats-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($next)): ?>
                    <div class="pageSuiv"><a href="/importgames/backoff/cats-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/cats-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                <?php endif;
                // Si le nombre de pages de pages est supérieur à 1 (voir categories.php ligne 117),
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php // on affiche le nombre de pages avec leurs liens
                    for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/cats-page-<?= $i ?>" id="lienPageTop<?= $i ?>"><?= $i ?></a></span>
                    <?php endfor;
                } ?>
            </div>
        <?php } ?>
        <div class="tableScroll">
            <table>
                <thead>
                    <tr>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triCatId">
                                    <span>Identifiant</span><i id="arrowDownCatId" class="fa fa-long-arrow-down"></i><i id="arrowUpCatId" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triCatTitre">
                                    <span>Titre</span><i id="arrDwnCatTitre" class="fa fa-long-arrow-down"></i><i id="arrUpCatTitre" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <?php if(in_array("3", $prv)) { ?>
                            <th>Options</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($cats as $cat): ?>
        	        <tr>
        	            <td><?= htmlspecialchars($cat["id"]) ?></td>
        	            <td>
                            <?php if($cat["titre"]): echo htmlspecialchars($cat["titre"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <?php if(in_array("3", $prv)) { ?>
            	            <td>
                                <a href="/importgames/backoff/modifcat-<?= htmlspecialchars($cat["id"]) ?>" class="btnModif"><?php if($cat["titre"]): ?><i class="fa fa-pencil-square-o"></i>Modifier<?php else: ?><i class="fa fa-exchange"></i>Remplacer<?php endif; ?></a>
                                <?php if($cat["titre"]) { ?>
                                    <form class="formReset" method="POST">
                                        <button type="submit" id="resetCat<?= htmlspecialchars($cat["id"]) ?>" class="btnReset" name="resetCat" value="<?= htmlspecialchars($cat["id"]) ?>"><i class="fa fa-trash-o"></i>Supprimer</button>
                                        <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
                                        <input type="hidden" name="formToken" value="<?= $token ?>" />
                                    </form>
                                <?php } ?>
                            </td>
                        <?php } ?>
        	        </tr>
        	        <?php endforeach; ?>
            	</tbody>
            </table>
        </div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
            	<?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/cats-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/cats-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
            	<?php elseif(isset($next)): ?>
                	<div class="pageSuiv"><a href="/importgames/backoff/cats-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/cats-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
            	<?php endif;
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/cats-page-<?= $i ?>" id="lienPage<?= $i ?>"><?= $i ?></a></span>
                    <?php endfor;
                } ?>
            </div>
        <?php }
    endif; ?>
    <div class="backLink"><a href="/importgames/backoff/tableau-de-bord"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Accueil</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>