<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li><a href="/importgames/backoff/cats-page-1">Liste des catégories</a></li>
        <li class="titreFil">
            <?php if(in_array("3", $prv)):
                if(isset($catId)):
                    if(!isset($cat["id"])): ?>
                        Aucun contenu trouvé
                    <?php elseif($cat["titre"]): ?>
                        Modifier catégorie <?= htmlspecialchars($cat["titre"]);
                    else: ?>
                        Remplacer catégorie #<?= htmlspecialchars(str_pad($cat["id"], 3, "0", STR_PAD_LEFT));
                    endif;
                else: ?>
                    Erreur adresse HTTP
                <?php endif;
            else: ?>
                Autorisation refusée
            <?php endif; ?>
        </li>
        <li class="titreFil300" title="<?php if(in_array("3", $prv)): if(isset($catId)): if(!isset($cat["id"])): ?>Aucun contenu trouvé<?php elseif($cat["titre"]): ?>Modifier catégorie <?= htmlspecialchars($cat["titre"]); else: ?>Remplacer catégorie #<?= htmlspecialchars(str_pad($cat["id"], 3, "0", STR_PAD_LEFT)); endif; else: ?>Erreur adresse HTTP<?php endif; else: ?>Autorisation refusée<?php endif; ?>">...</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerModifCat">
    <?php if(!in_array("3", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php elseif(!isset($catId)): ?>
        <div class="erreurHeader">
            <img src="/importgames/images/divers/warning.png" alt="imgWarning" />
            <h2>Erreur adresse HTTP</h2>
        </div>
    <?php elseif(!isset($cat["id"])): ?>
        <div class="erreurHeader">
            <img src="/importgames/images/divers/point_d_interrogation.png" alt="imgInterrogation" />
            <h2>Aucun contenu trouvé</h2>
        </div>
    <?php else: ?>
    	<h3><?php if($cat["titre"]): ?><i class="fa fa-pencil"></i>Modifier catégorie <?= htmlspecialchars($cat["titre"]) ?><?php else: ?><i class="fa fa-exchange"></i>Remplacer catégorie #<?= htmlspecialchars(str_pad($cat["id"], 3, "0", STR_PAD_LEFT)) ?><?php endif; ?></h3>
        <form method="POST">
            <div>
                <label for="titre">Titre :</label>
                <input type="text" id="titre" name="titre" value="<?php if(isset($_POST["titre"])) echo htmlspecialchars($_POST["titre"]); else echo htmlspecialchars($cat["titre"]); ?>" required />
                <?php if(isset($emptyTitre)): ?>
                    <p>Le <em>titre</em> ne peut pas être vide.</p>
                <?php elseif(isset($invalidTitre)): ?>
                    <p>Le <em>titre</em> ne doit comporter aucun chiffres ni caractères spéciaux et ne pas dépasser 16 caractères.</p>
                <?php endif; ?>
            </div>
            <input type="submit" class="btn" name="mdfCat" value="Valider" />
            <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
            <input type="hidden" name="formToken" value="<?= $token ?>" />
            <?php if(isset($verifError)): ?>
                <div class="msg"><p>Erreur de vérification.</p></div>
            <?php elseif(isset($refError)): ?>
                <div class="msg"><p>La requête ne provient pas du formulaire.</p></div>
            <?php endif; ?>
        </form>
        <?php if($cat["titre"]) { ?>
            <form class="formReset" method="POST">
                <button type="button" id="resetCat" class="btnReset"><i class="fa fa-trash-o"></i>Supprimer la catégorie</button>
                <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
                <input type="hidden" name="formResetToken" value="<?= $token ?>" />
                <?php if(isset($verifResetError)): ?>
                    <div><p>Erreur de vérification.</p></div>
                <?php elseif(isset($refResetError)): ?>
                    <div><p>La requête ne provient pas du formulaire.</p></div>
                <?php endif; ?>
            </form>
        <?php }
    endif; ?>
    <div class="backLink"><a href="/importgames/backoff/cats-page-1"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Retour</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>