<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="index" class="home">Accueil</a></li>
        <li>Mes commandes</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerCom">
    <?php if(!isset($page) || !$nbrComsUser[0]) { ?>
		<div class="comNull">
			<img src="images/divers/package.png" alt="imgPackage" />
			<h2>Aucune commande trouvée dans l'historique</h2>
		</div>
    <?php }
    else { ?>
    	<h3><i class="fa fa-chevron-right"></i>Mes commandes</h3>
	    <form class="formLines" method="POST">
	        <label for="affichageLignes">Afficher par : </label>
	        <select id="affichageLignes" name="affichageLignes">
	            <option value="5">5</option>
	            <option value="10">10</option>
	            <option value="25">25</option>
	            <option value="50">50</option>
	        </select>
	    </form>
        <div class="tableScroll">
		    <table>
		        <thead>
		            <tr>
		                <th>
		                    <form method="POST">
		                    	<span id="noTriNum" class="spanNoTri">Commande</span>
		                        <button id="triNum" class="btnTri" type="submit" name="triNum"><span class="spanTri">Commande</span><i id="arrowDownNum" class="fa fa-long-arrow-down"></i><i id="arrowUpNum" class="fa fa-long-arrow-up"></i></button>
		                    </form>
		                </th>
		                <th>
		                    <form method="POST">
		                    	<span id="noTriDate" class="spanNoTri">Date</span>
		                        <button id="triDate" class="btnTri" type="submit" name="triDate"><span class="spanTri">Date</span><i id="arrowDownDate" class="fa fa-long-arrow-down"></i><i id="arrowUpDate" class="fa fa-long-arrow-up"></i></button>
		                    </form>
		                </th>
		                <th>
		                    <form method="POST">
		                    	<span id="noTriTotal" class="spanNoTri">Total</span>
		                        <button id="triTotal" class="btnTri" type="submit" name="triTotal"><span class="spanTri">Total</span><i id="arrowDownTotal" class="fa fa-long-arrow-down"></i><i id="arrowUpTotal" class="fa fa-long-arrow-up"></i></button>
		                    </form>
		                </th>
		                <th>Options</th>
		            </tr>
		        </thead>
		        <tbody>
			        <?php foreach($coms as $com): ?>
			        <tr>
			            <td>#<?= htmlentities(str_pad($com["numero"], 4, "0", STR_PAD_LEFT)) ?></td>
			            <td><?= htmlentities($com["date_co"]) ?></td>
			            <td><?= htmlentities(str_replace(".", ",", $com["total"])) ?>€</td>
			            <td><a href="detailco-<?= htmlentities($com["id"]) ?>" class="btnDetails">Détails</a></td>
			        </tr>
			        <?php endforeach; ?>
		    	</tbody>
		    </table>
		</div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
				<?php // Si les variables "next" et "prev" sont déclarées et différentes de NULL on affiche les liens "<< Precédent" et "Suivant >>" (voir commandes.php lignes 238 et 239)
			    if(isset($prev) && isset($next)) { ?>
			        <div class="pagePrec"><a href="commandes-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
			        <div class="pageSuiv"><a href="commandes-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
				<?php }

				// Voir commande.php ligne 232
			    elseif(isset($next)) { ?>
			    	<div class="pageSuiv"><a href="commandes-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
			    <?php }

				// Voir commande.php ligne 245
				elseif(isset($prev)) { ?>
			        <div class="pagePrec"><a href="commandes-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
				<?php }

			    // Si le nombre de pages de pages est supérieur à 1 (voir commandes.php ligne 222),
			    if($nbrPages > 1) { ?>
			        <span>Pages : </span>

			        <?php // on affiche le nombre de pages avec leurs liens
			        for($i = 1 ; $i <= $nbrPages ; $i++): ?>
			            <span class="liensPages"><a href="commandes-page-<?= $i ?>" id="lienPage<?= $i ?>"><?= $i ?></a></span>
			        <?php endfor;
			    } ?>
            </div>
        <?php }
    } ?>
    <div class="backLink"><a href="/importgames/index"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Accueil</a></div>
</main>