<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="index" class="home">Accueil</a></li>
        <li><a href="profil">Mes informations</a></li>
        <li class="titreFil">Modifier mon adresse</li>
        <li class="titreFil300" title="Modifier mon adresse">M...</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerAdresse">
    <h3><i class="fa fa-chevron-right"></i>Modifier mon adresse</h3>
    <form method="POST">
        <div>
            <label for="nom">Nom :</label>
            <input type="text" id="nom" name="nom" value="<?php if(isset($_POST["nom"])) { echo htmlspecialchars($_POST["nom"]); } else { echo htmlspecialchars($user["nom"]); } ?>" required />
            <?php if(isset($emptyNom)) { ?>
                <p>Le <em>nom</em> ne peut pas être vide.</p>
            <?php }
            elseif(isset($invalidNom)) { ?>
                <p>Le <em>nom</em> doit contenir au moins 3 caractères et ne comporter aucun chiffres ni caractères spéciaux.</p>
            <?php } ?>
        </div>
        <div>
            <label for="prenom">Prénom :</label>
            <input type="text" id="prenom" name="prenom" value="<?php if(isset($_POST["prenom"])) { echo htmlspecialchars($_POST["prenom"]); } else { echo htmlspecialchars($user["prenom"]); } ?>" required />
            <?php if(isset($emptyPrenom)) { ?>
                <p>Le <em>prénom</em> ne peut pas être vide.</p>
            <?php }
            elseif(isset($invalidPrenom)) { ?>
                <p>Le <em>prénom</em> doit contenir au moins 3 caractères et ne comporter aucun chiffres ni caractères spéciaux.</p>
            <?php } ?>
        </div>
        <div>
            <label for="adresse">Adresse :</label>
            <input type="text" id="adresse" name="adresse" value="<?php if(isset($_POST["adresse"])) { echo htmlspecialchars($_POST["adresse"]); } else { echo htmlspecialchars($user["adresse"]); } ?>" required />
            <?php if(isset($emptyAdress)) { ?>
                <p>L'<em>adresse</em> ne peut pas être vide.</p>
            <?php }
            elseif(isset($invalidAdresse)) { ?>
                <p>L'<em>adresse</em> n'est pas valide.</p>
            <?php } ?>
        </div>
        <div>
            <label for="codePostal">Code postal :</label>
            <input type="text" id="codePostal" name="codePostal" value="<?php if(isset($_POST["codePostal"])) { echo $_POST["codePostal"]; } else { echo htmlentities($user["code_postal"]); } ?>" required />
            <?php if(isset($emptyCdPost)) { ?>
                <p>Le <em>code postal</em> ne peut pas être vide.</p>
            <?php }
            elseif(isset($invalidCdPost)) { ?>
                <p>Le <em>code postal</em> n'est pas valide.</p>
            <?php } ?>
        </div>
        <div>
            <label for="ville">Ville :</label>
            <input type="text" id="ville" name="ville" value="<?php if(isset($_POST["ville"])) { echo htmlspecialchars($_POST["ville"]); } else { echo htmlspecialchars($user["ville"]); } ?>" required />
            <?php if(isset($emptyVille)) { ?>
                <p>La <em>ville</em> ne peut pas être vide.</p>
            <?php }
            elseif(isset($invalidVille)) { ?>
                <p>La <em>ville</em> n'est pas valide.</p>
            <?php } ?>
        </div>
        <div>
            <label for="pays">Pays :</label>
            <select id="pays" name="pays" required>
                <option value="">Choisissez un pays</option>
                <option value="0">Aucun</option>
                <option value="AF">AFGHANISTAN</option>
                <option value="ZA">AFRIQUE DU SUD</option>
                <option value="AX">ÅLAND, ÎLES</option>
                <option value="AL">ALBANIE</option>
                <option value="DZ">ALGÉRIE</option>
                <option value="DE">ALLEMAGNE</option>
                <option value="AD">ANDORRE</option>
                <option value="AO">ANGOLA</option>
                <option value="AI">ANGUILLA</option>
                <option value="AQ">ANTARCTIQUE</option>
                <option value="AG">ANTIGUA-ET-BARBUDA</option>
                <option value="AN">ANTILLES NÉERLANDAISES</option>
                <option value="SA">ARABIE SAOUDITE</option>
                <option value="AR">ARGENTINE</option>
                <option value="AM">ARMÉNIE</option>
                <option value="AW">ARUBA</option>
                <option value="AU">AUSTRALIE</option>
                <option value="AT">AUTRICHE</option>
                <option value="AZ">AZERBAÏDJAN</option>
                <option value="BS">BAHAMAS</option>
                <option value="BH">BAHREÏN</option>
                <option value="BD">BANGLADESH</option>
                <option value="BB">BARBADE</option>
                <option value="BY">BÉLARUS</option>
                <option value="BE">BELGIQUE</option>
                <option value="BZ">BELIZE</option>
                <option value="BJ">BÉNIN</option>
                <option value="BM">BERMUDES</option>
                <option value="BT">BHOUTAN</option>
                <option value="BO">BOLIVIE</option>
                <option value="BA">BOSNIE-HERZÉGOVINE</option>
                <option value="BW">BOTSWANA</option>
                <option value="BV">BOUVET, ÎLE</option>
                <option value="BR">BRÉSIL</option>
                <option value="BN">BRUNÉI DARUSSALAM</option>
                <option value="BG">BULGARIE</option>
                <option value="BF">BURKINA FASO</option>
                <option value="BI">BURUNDI</option>
                <option value="KY">CAÏMANES, ÎLES</option>
                <option value="KH">CAMBODGE</option>
                <option value="CM">CAMEROUN</option>
                <option value="CA">CANADA</option>
                <option value="CV">CAP-VERT</option>
                <option value="CF">CENTRAFRICAINE, RÉPUBLIQUE</option>
                <option value="CL">CHILI</option>
                <option value="CN">CHINE</option>
                <option value="CX">CHRISTMAS, ÎLE</option>
                <option value="CY">CHYPRE</option>
                <option value="CC">COCOS (KEELING), ÎLES</option>
                <option value="CO">COLOMBIE</option>
                <option value="KM">COMORES</option>
                <option value="CG">CONGO</option>
                <option value="CD">CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU</option>
                <option value="CK">COOK, ÎLES</option>
                <option value="KR">CORÉE, RÉPUBLIQUE DE</option>
                <option value="KP">CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE</option>
                <option value="CR">COSTA RICA</option>
                <option value="CI">CÔTE D'IVOIRE</option>
                <option value="HR">CROATIE</option>
                <option value="CU">CUBA</option>
                <option value="DK">DANEMARK</option>
                <option value="DJ">DJIBOUTI</option>
                <option value="DO">DOMINICAINE, RÉPUBLIQUE</option>
                <option value="DM">DOMINIQUE</option>
                <option value="EG">ÉGYPTE</option>
                <option value="SV">EL SALVADOR</option>
                <option value="AE">ÉMIRATS ARABES UNIS</option>
                <option value="EC">ÉQUATEUR</option>
                <option value="ER">ÉRYTHRÉE</option>
                <option value="ES">ESPAGNE</option>
                <option value="EE">ESTONIE</option>
                <option value="US">ÉTATS-UNIS</option>
                <option value="ET">ÉTHIOPIE</option>
                <option value="FK">FALKLAND, ÎLES (MALVINAS)</option>
                <option value="FO">FÉROÉ, ÎLES</option>
                <option value="FJ">FIDJI</option>
                <option value="FI">FINLANDE</option>
                <option value="FR" selected="selected">FRANCE</option>
                <option value="GA">GABON</option>
                <option value="GM">GAMBIE</option>
                <option value="GE">GÉORGIE</option>
                <option value="GS">GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD</option>
                <option value="GH">GHANA</option>
                <option value="GI">GIBRALTAR</option>
                <option value="GR">GRÈCE</option>
                <option value="GD">GRENADE</option>
                <option value="GL">GROENLAND</option>
                <option value="GP">GUADELOUPE</option>
                <option value="GU">GUAM</option>
                <option value="GT">GUATEMALA</option>
                <option value="GG">GUERNESEY</option>
                <option value="GN">GUINÉE</option>
                <option value="GW">GUINÉE-BISSAU</option>
                <option value="GQ">GUINÉE ÉQUATORIALE</option>
                <option value="GY">GUYANA</option>
                <option value="GF">GUYANE FRANÇAISE</option>
                <option value="HT">HAÏTI</option>
                <option value="HM">HEARD, ÎLE ET MCDONALD, ÎLES</option>
                <option value="HN">HONDURAS</option>
                <option value="HK">HONG-KONG</option>
                <option value="HU">HONGRIE</option>
                <option value="IM">ÎLE DE MAN</option>
                <option value="UM">ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS</option>
                <option value="VG">ÎLES VIERGES BRITANNIQUES</option>
                <option value="VI">ÎLES VIERGES DES ÉTATS-UNIS</option>
                <option value="IN">INDE</option>
                <option value="ID">INDONÉSIE</option>
                <option value="IR">IRAN, RÉPUBLIQUE ISLAMIQUE D'</option>
                <option value="IQ">IRAQ</option>
                <option value="IE">IRLANDE</option>
                <option value="IS">ISLANDE</option>
                <option value="IL">ISRAËL</option>
                <option value="IT">ITALIE</option>
                <option value="JM">JAMAÏQUE</option>
                <option value="JP">JAPON</option>
                <option value="JE">JERSEY</option>
                <option value="JO">JORDANIE</option>
                <option value="KZ">KAZAKHSTAN</option>
                <option value="KE">KENYA</option>
                <option value="KG">KIRGHIZISTAN</option>
                <option value="KI">KIRIBATI</option>
                <option value="KW">KOWEÏT</option>
                <option value="LA">LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE</option>
                <option value="LS">LESOTHO</option>
                <option value="LV">LETTONIE</option>
                <option value="LB">LIBAN</option>
                <option value="LR">LIBÉRIA</option>
                <option value="LY">LIBYENNE, JAMAHIRIYA ARABE</option>
                <option value="LI">LIECHTENSTEIN</option>
                <option value="LT">LITUANIE</option>
                <option value="LU">LUXEMBOURG</option>
                <option value="MO">MACAO</option>
                <option value="MK">MACÉDOINE, L'EX-RÉPUBLIQUE YOUGOSLAVE DE</option>
                <option value="MG">MADAGASCAR</option>
                <option value="MY">MALAISIE</option>
                <option value="MW">MALAWI</option>
                <option value="MV">MALDIVES</option>
                <option value="ML">MALI</option>
                <option value="MT">MALTE</option>
                <option value="MP">MARIANNES DU NORD, ÎLES</option>
                <option value="MA">MAROC</option>
                <option value="MH">MARSHALL, ÎLES</option>
                <option value="MQ">MARTINIQUE</option>
                <option value="MU">MAURICE</option>
                <option value="MR">MAURITANIE</option>
                <option value="YT">MAYOTTE</option>
                <option value="MX">MEXIQUE</option>
                <option value="FM">MICRONÉSIE, ÉTATS FÉDÉRÉS DE</option>
                <option value="MD">MOLDOVA, RÉPUBLIQUE DE</option>
                <option value="MC">MONACO</option>
                <option value="MN">MONGOLIE</option>
                <option value="MS">MONTSERRAT</option>
                <option value="MZ">MOZAMBIQUE</option>
                <option value="MM">MYANMAR</option>
                <option value="NA">NAMIBIE</option>
                <option value="NR">NAURU</option>
                <option value="NP">NÉPAL</option>
                <option value="NI">NICARAGUA</option>
                <option value="NE">NIGER</option>
                <option value="NG">NIGÉRIA</option>
                <option value="NU">NIUÉ</option>
                <option value="NF">NORFOLK, ÎLE</option>
                <option value="NO">NORVÈGE</option>
                <option value="NC">NOUVELLE-CALÉDONIE</option>
                <option value="NZ">NOUVELLE-ZÉLANDE</option>
                <option value="IO">OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L'</option>
                <option value="OM">OMAN</option>
                <option value="UG">OUGANDA</option>
                <option value="UZ">OUZBÉKISTAN</option>
                <option value="PK">PAKISTAN</option>
                <option value="PW">PALAOS</option>
                <option value="PS">PALESTINIEN OCCUPÉ, TERRITOIRE</option>
                <option value="PA">PANAMA</option>
                <option value="PG">PAPOUASIE-NOUVELLE-GUINÉE</option>
                <option value="PY">PARAGUAY</option>
                <option value="NL">PAYS-BAS</option>
                <option value="PE">PÉROU</option>
                <option value="PH">PHILIPPINES</option>
                <option value="PN">PITCAIRN</option>
                <option value="PL">POLOGNE</option>
                <option value="PF">POLYNÉSIE FRANÇAISE</option>
                <option value="PR">PORTO RICO</option>
                <option value="PT">PORTUGAL</option>
                <option value="QA">QATAR</option>
                <option value="RE">RÉUNION</option>
                <option value="RO">ROUMANIE</option>
                <option value="GB">ROYAUME-UNI</option>
                <option value="RU">RUSSIE, FÉDÉRATION DE</option>
                <option value="RW">RWANDA</option>
                <option value="EH">SAHARA OCCIDENTAL</option>
                <option value="SH">SAINTE-HÉLÈNE</option>
                <option value="LC">SAINTE-LUCIE</option>
                <option value="KN">SAINT-KITTS-ET-NEVIS</option>
                <option value="SM">SAINT-MARIN</option>
                <option value="PM">SAINT-PIERRE-ET-MIQUELON</option>
                <option value="VA">SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)</option>
                <option value="VC">SAINT-VINCENT-ET-LES GRENADINES</option>
                <option value="SB">SALOMON, ÎLES</option>
                <option value="WS">SAMOA</option>
                <option value="AS">SAMOA AMÉRICAINES</option>
                <option value="ST">SAO TOMÉ-ET-PRINCIPE</option>
                <option value="SN">SÉNÉGAL</option>
                <option value="CS">SERBIE-ET-MONTÉNÉGRO</option>
                <option value="SC">SEYCHELLES</option>
                <option value="SL">SIERRA LEONE</option>
                <option value="SG">SINGAPOUR</option>
                <option value="SK">SLOVAQUIE</option>
                <option value="SI">SLOVÉNIE</option>
                <option value="SO">SOMALIE</option>
                <option value="SD">SOUDAN</option>
                <option value="LK">SRI LANKA</option>
                <option value="SE">SUÈDE</option>
                <option value="CH">SUISSE</option>
                <option value="SR">SURINAME</option>
                <option value="SJ">SVALBARD ET ÎLE JAN MAYEN</option>
                <option value="SZ">SWAZILAND</option>
                <option value="SY">SYRIENNE, RÉPUBLIQUE ARABE</option>
                <option value="TJ">TADJIKISTAN</option>
                <option value="TW">TAÏWAN, PROVINCE DE CHINE</option>
                <option value="TZ">TANZANIE, RÉPUBLIQUE-UNIE DE</option>
                <option value="TD">TCHAD</option>
                <option value="CZ">TCHÈQUE, RÉPUBLIQUE</option>
                <option value="TF">TERRES AUSTRALES FRANÇAISES</option>
                <option value="TH">THAÏLANDE</option>
                <option value="TL">TIMOR-LESTE</option>
                <option value="TG">TOGO</option>
                <option value="TK">TOKELAU</option>
                <option value="TO">TONGA</option>
                <option value="TT">TRINITÉ-ET-TOBAGO</option>
                <option value="TN">TUNISIE</option>
                <option value="TM">TURKMÉNISTAN</option>
                <option value="TC">TURKS ET CAÏQUES, ÎLES</option>
                <option value="TR">TURQUIE</option>
                <option value="TV">TUVALU</option>
                <option value="UA">UKRAINE</option>
                <option value="UY">URUGUAY</option>
                <option value="VU">VANUATU</option>
                <option value="VE">VENEZUELA</option>
                <option value="VN">VIET NAM</option>
                <option value="WF">WALLIS ET FUTUNA</option>
                <option value="YE">YÉMEN</option>
                <option value="ZM">ZAMBIE</option>
                <option value="ZW">ZIMBABWE</option>
            </select>
            <?php if(isset($emptyPays)) { ?>
                <p>Le champ de saisie <em>pays</em> ne peut pas être vide.</p>
            <?php }
            elseif(isset($invalidPays)) { ?>
                <p>Le champ de saisie <em>pays</em> n'est pas valide.</p>
            <?php } ?>
        </div>
        <div>
            <label for="tel">Téléphone :</label>
            <input type="tel" id="tel" name="tel" value="<?php if(isset($_POST["tel"])) { echo $_POST["tel"]; } else { echo htmlentities($user["tel"]); } ?>" required />
            <?php if(isset($emptyTel)) { ?>
                <p>Le <em>numéro de téléphone</em> ne peut pas être vide.</p>
            <?php }
            elseif(isset($invalidTel)) { ?>
                <p>Le <em>numéro de téléphone</em> n'est pas valide.</p>
            <?php } ?>
        </div>
        <input type="submit" class="btnModif" name="modifAdresse" value="Valider" />
        <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
        <input type="hidden" name="formToken" value="<?= $token ?>" />
        <?php if(isset($verifError)) { ?>
            <div class="msgAdress"><p>Erreur de vérification.</p></div>
        <?php }
        elseif(isset($refError)) { ?>
            <div class="msgAdress"><p>La requête ne provient pas du formulaire.</p></div>
        <?php } ?>
    </form>
    <?php if($user["nom"]) { ?>
        <form class="formReset" method="POST">
            <button type="button" id="resetAdress" class="btnReset">Supprimer l'adresse</button>
            <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
            <input type="hidden" name="formResetToken" value="<?= $token ?>" />
            <?php if(isset($verifResetError)) { ?>
                <div><p>Erreur de vérification.</p></div>
            <?php }
            elseif(isset($refResetError)) { ?>
                <div><p>La requête ne provient pas du formulaire.</p></div>
            <?php } ?>
        </form>
    <?php } ?>
    <div class="backLink"><a href="/importgames/profil"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Retour</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>