<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/index" class="home">Accueil</a></li>
        <li>Page introuvable</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerErreur404">
    <div>
    	<img src="/importgames/images/divers/404-error.png" alt="img404" />
    	<h2>La page que vous demandez est introuvable.</h2>
    </div>
    <div class="backLink"><a href="/importgames/index"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Accueil</a></div>
</main>