<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li>Liste des partenaires</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerListe">
    <?php if(!in_array("31", $prv) && !in_array("32", $prv) && !in_array("33", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php elseif(isset($page)): ?>
    	<h3><i class="fa fa-list-ul"></i>Liste des partenaires</h3>
        <?php if(in_array("32", $prv)) { ?>
            <h3><a href="/importgames/backoff/ajoutpartn"><i class="fa fa-plus"></i>Ajouter un partenaire</a></h3>
        <?php } ?>
        <form class="formLines" method="POST">
            <label for="lignesPartn">Afficher par : </label>
            <select id="lignesPartn" name="lignesPartn">
                <?php if($nbrPartns[0] <= 100) { ?>
                <option value="5">5</option>
                <?php }
                if($nbrPartns[0] <= 250) { ?>
                <option value="10">10</option>
                <?php } ?>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                <?php if($nbrPartns[0] > 100) { ?>
                <option value="250">250</option>
                <?php }
                if($nbrPartns[0] > 250) { ?>
                <option value="500">500</option>
                <?php } ?>
            </select>
        </form>
        <div>Résultats <?= $resultDebut ?> à <?= htmlspecialchars($resultFin) ?> sur <?= htmlspecialchars($nbrPartns[0]) ?></div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
                <?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/partns-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/partns-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($next)): ?>
                    <div class="pageSuiv"><a href="/importgames/backoff/partns-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/partns-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                <?php endif;
                // Si le nombre de pages de pages est supérieur à 1 (voir partenaires.php ligne 117),
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php // on affiche le nombre de pages avec leurs liens
                    for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/partns-page-<?= $i ?>" id="lienPageTop<?= $i ?>"><?= $i ?></a></span>
                    <?php endfor;
                } ?>
            </div>
        <?php } ?>
        <div class="tableScroll">
            <table>
                <thead>
                    <tr>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triPartnId">
                                    <span>Id</span><i id="arrowDownPartnId" class="fa fa-long-arrow-down"></i><i id="arrowUpPartnId" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triPartnNom">
                                    <span>Nom</span><i id="arrDwnPrtnNom" class="fa fa-long-arrow-down"></i><i id="arrUpPrtnNom" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triPartnImg">
                                    <span>Image</span><i id="arrDwnPrtnImg" class="fa fa-long-arrow-down"></i><i id="arrUpPrtnImg" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triPartnUrl">
                                    <span>Adresse web</span><i id="arrDwnPrtnUrl" class="fa fa-long-arrow-down"></i><i id="arrUpPrtnUrl" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <?php if(in_array("33", $prv)) { ?>
                            <th>Options</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($partns as $partn): ?>
        	        <tr>
        	            <td><?= htmlspecialchars($partn["id"]) ?></td>
        	            <td>
                            <?php if($partn["nom"]): echo htmlspecialchars($partn["nom"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($partn["image"]): ?>
                                <a href="<?= htmlspecialchars($partn["image"]) ?>" target="_blank"><img src="<?= htmlspecialchars($partn["image"]) ?>" alt="imgPartn" /></a>
                            <?php else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($partn["url"]): ?>
                                <a href="<?= htmlspecialchars($partn["url"]) ?>" target="_blank"><?= htmlspecialchars($partn["url"]) ?></a>
                            <?php else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <?php if(in_array("33", $prv)) { ?>
            	            <td>
                                <a href="/importgames/backoff/modifpartn-<?= htmlspecialchars($partn["id"]) ?>" class="btnModif"><?php if($partn["nom"]): ?><i class="fa fa-pencil-square-o"></i>Modifier<?php else: ?><i class="fa fa-exchange"></i>Remplacer<?php endif; ?></a>
                                <?php if($partn["nom"]) { ?>
                                    <form class="formReset" method="POST">
                                        <button type="submit" id="resetPartn<?= htmlspecialchars($partn["id"]) ?>" class="btnReset" name="resetPartn" value="<?= htmlspecialchars($partn["id"]) ?>"><i class="fa fa-trash-o"></i>Supprimer</button>
                                        <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
                                        <input type="hidden" name="formToken" value="<?= $token ?>" />
                                    </form>
                                <?php } ?>
                            </td>
                        <?php } ?>
        	        </tr>
        	        <?php endforeach; ?>
            	</tbody>
            </table>
        </div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
            	<?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/partns-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/partns-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
            	<?php elseif(isset($next)): ?>
                	<div class="pageSuiv"><a href="/importgames/backoff/partns-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/partns-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
            	<?php endif;
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/partns-page-<?= $i ?>" id="lienPage<?= $i ?>"><?= $i ?></a></span>
            		<?php endfor;
                } ?>
            </div>
        <?php }
    endif; ?>
    <div class="backLink"><a href="/importgames/backoff/tableau-de-bord"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Accueil</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>