<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li><a href="/importgames/backoff/imgs-page-1">Liste des images</a></li>
        <li class="titreFil">
            <?php if(in_array("14", $prv)):
                if(isset($imgId)):
                    if(!isset($img["id"])): ?>
                        Aucun contenu trouvé
                    <?php elseif($img["produit_id"]): ?>
                        Modifier image #<?= htmlspecialchars(str_pad($img["id"], 4, "0", STR_PAD_LEFT));
                    else: ?>
                        Remplacer image #<?= htmlspecialchars(str_pad($img["id"], 4, "0", STR_PAD_LEFT));
                    endif;
                else: ?>
                    Erreur adresse HTTP
                <?php endif;
            else: ?>
                Autorisation refusée
            <?php endif; ?>
        </li>
        <li class="titreFil300" title="<?php if(in_array("14", $prv)): if(isset($imgId)): if(!isset($img["id"])): ?>Aucun contenu trouvé<?php elseif($img["produit_id"]): ?>Modifier image #<?= htmlspecialchars(str_pad($img["id"], 4, "0", STR_PAD_LEFT)); else: ?>Remplacer image #<?= htmlspecialchars(str_pad($img["id"], 4, "0", STR_PAD_LEFT)); endif; else: ?>Erreur adresse HTTP<?php endif; else: ?>Autorisation refusée<?php endif; ?>">...</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerModif">
    <?php if(!in_array("14", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php elseif(!isset($imgId)): ?>
        <div class="erreurHeader">
            <img src="/importgames/images/divers/warning.png" alt="imgWarning" />
            <h2>Erreur adresse HTTP</h2>
        </div>
    <?php elseif(!isset($img["id"])): ?>
        <div class="erreurHeader">
            <img src="/importgames/images/divers/point_d_interrogation.png" alt="imgInterrogation" />
            <h2>Aucun contenu trouvé</h2>
        </div>
    <?php else: ?>
    	<h3><?php if($img["produit_id"]): ?><i class="fa fa-pencil"></i>Modifier<?php else: ?><i class="fa fa-exchange"></i>Remplacer<?php endif; ?> image #<?= htmlspecialchars(str_pad($img["id"], 4, "0", STR_PAD_LEFT)) ?></h3>
        <form enctype="multipart/form-data" method="POST">
            <div>
                <label for="prodId">Identifiant produit :</label>
                <select id="prodId" name="prodId" required>
                    <?php foreach($prods as $prod): ?>
                        <option value="<?= htmlspecialchars($prod["id"]) ?>">
                            <?= htmlspecialchars($prod["id"]) ?> - <?= htmlspecialchars($prod["titre"]) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <?php if(isset($emptyProdId)): ?>
                    <p>L'<em>identifiant produit</em> ne peut pas être vide.</p>
                <?php elseif(isset($invalidProdId)): ?>
                    <p>L'<em>identifiant produit</em> n'est pas valide.</p>
                <?php endif; ?>
            </div>
            <div>
                <input type="hidden" name="MAX_FILE_SIZE" value="5000000" />
                <label for="imgUrl">Image :</label>
                <?php if($img["url"]) { ?>
                    <i>(<a href="<?= htmlspecialchars($img["url"])?>" target="_blank">Lien vers l'image actuelle</a>)</i>
                <?php } ?>
                <input type="file" id="imgUrl" name="imgUrl" accept=".gif, .jpeg, .jpg, .png, .svg" <?php if(!$img["produit_id"]) { ?>required=""<?php } ?> />
                <?php if(isset($emptyImg)): ?>
                    <p>Le fichier <em>image</em> ne peut pas être vide ou dépasser la taille de 5000 Ko.</p>
                <?php elseif(isset($errorImg)): ?>
                    <p>Une erreur s'est produite lors de la vérification du fichier.</p>
                <?php endif; ?>
            </div>
            <input type="submit" class="btn" name="mdfImg" value="Valider" />
            <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
            <input type="hidden" name="formToken" value="<?= $token ?>" />
            <?php if(isset($verifError)): ?>
                <div class="msg"><p>Erreur de vérification.</p></div>
            <?php elseif(isset($refError)): ?>
                <div class="msg"><p>La requête ne provient pas du formulaire.</p></div>
            <?php endif; ?>
        </form>
        <?php if($img["produit_id"]) { ?>
            <form class="formReset" method="POST">
                <button type="button" id="resetImg" class="btnReset"><i class="fa fa-trash-o"></i>Supprimer l'image</button>
                <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
                <input type="hidden" name="formResetToken" value="<?= $token ?>" />
                <?php if(isset($verifResetError)): ?>
                    <div><p>Erreur de vérification.</p></div>
                <?php elseif(isset($refResetError)): ?>
                    <div><p>La requête ne provient pas du formulaire.</p></div>
                <?php endif; ?>
            </form>
        <?php }
    endif; ?>
    <div class="backLink"><a href="/importgames/backoff/imgs-page-1"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Retour</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>