<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li>Liste des recherches</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerListe">
    <?php if(!in_array("29", $prv) && !in_array("30", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php elseif(isset($page)): ?>
    	<h3><i class="fa fa-list-ul"></i>Liste des recherches</h3>
        <form class="formLines" method="POST">
            <label for="lignesSearch">Afficher par : </label>
            <select id="lignesSearch" name="lignesSearch">
                <?php if($nbrSearchs[0] <= 100) { ?>
                <option value="5">5</option>
                <?php }
                if($nbrSearchs[0] <= 250) { ?>
                <option value="10">10</option>
                <?php } ?>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                <?php if($nbrSearchs[0] > 100) { ?>
                <option value="250">250</option>
                <?php }
                if($nbrSearchs[0] > 250) { ?>
                <option value="500">500</option>
                <?php } ?>
            </select>
        </form>
        <div>Résultats <?= $resultDebut ?> à <?= htmlspecialchars($resultFin) ?> sur <?= htmlspecialchars($nbrSearchs[0]) ?></div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
                <?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/recs-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/recs-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($next)): ?>
                    <div class="pageSuiv"><a href="/importgames/backoff/recs-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/recs-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                <?php endif;
                // Si le nombre de pages de pages est supérieur à 1 (voir recherches.php ligne 141),
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php // on affiche le nombre de pages avec leurs liens
                    for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/recs-page-<?= $i ?>" id="lienPageTop<?= $i ?>"><?= $i ?></a></span>
                    <?php endfor;
                } ?>
            </div>
        <?php } ?>
        <div class="tableScroll">
            <table>
                <thead>
                    <tr>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triRecId">
                                    <span>Id</span><i id="arrowDownRecId" class="fa fa-long-arrow-down"></i><i id="arrowUpRecId" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triRecTexte">
                                    <span>Texte</span><i id="arrDwnRecTxt" class="fa fa-long-arrow-down"></i><i id="arrUpRecTxt" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triRecUser">
                                    <span>Id utilisateur</span><i id="arrDwnRecUser" class="fa fa-long-arrow-down"></i><i id="arrUpRecUser" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triRecDate">
                                    <span>Date</span><i id="arrDwnRecDate" class="fa fa-long-arrow-down"></i><i id="arrUpRecDate" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <?php if(in_array("30", $prv)) { ?>
                            <th>Options</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($searchs as $search): ?>
        	        <tr>
        	            <td><?= htmlspecialchars($search["id"]) ?></td>
        	            <td><?= htmlspecialchars($search["texte"]) ?></td>
                        <td class="noWrap">
                            <?php if($search["user_id"]): echo htmlspecialchars($search["user_id"]); ?> - 
                                <?php if(substr($search["date_rec"], 0, -9) < getDatebyId($search["user_id"])): ?>
                                    <i>Compte remplacé</i>
                                <?php elseif(!getNamebyId($search["user_id"])): ?>
                                    <i>Compte supprimé</i>
                                <?php else: echo htmlspecialchars(getNamebyId($search["user_id"]));
                                endif;
                            else: ?>
                                <i>Invité</i>
                            <?php endif; ?>
                        </td>
                        <td><?= htmlspecialchars(date("d/m/Y H:i", strtotime($search["date_rec"]))) ?></td>
                        <?php if(in_array("30", $prv)) { ?>
            	            <td>
                                <div class="displayForm"></div>
                                <form class="formReset" method="POST">
                                    <button type="submit" id="resetSearch<?= htmlspecialchars($search["id"]) ?>" class="btnReset" name="resetSearch" value="<?= htmlspecialchars($search["id"]) ?>"><i class="fa fa-trash-o"></i>Supprimer</button>
                                    <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
                                    <input type="hidden" name="formToken" value="<?= $token ?>" />
                                </form>
                            </td>
                        <?php } ?>
        	        </tr>
        	        <?php endforeach; ?>
            	</tbody>
            </table>
        </div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
            	<?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/recs-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/recs-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
            	<?php elseif(isset($next)): ?>
                	<div class="pageSuiv"><a href="/importgames/backoff/recs-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/recs-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
            	<?php endif;
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/recs-page-<?= $i ?>" id="lienPage<?= $i ?>"><?= $i ?></a></span>
            		<?php endfor;
                } ?>
            </div>
        <?php }
    endif; ?>
    <div class="backLink"><a href="/importgames/backoff/tableau-de-bord"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Accueil</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>