<!-- BREADCRUMB -->
<nav class="filAriane">
    <ul>
        <li><a href="/importgames/backoff/tableau-de-bord" class="home">Accueil</a></li>
        <li class="titreFil">Liste des administrateurs</li>
        <li class="titreFil300" title="Liste des administrateurs">Liste des administrat...</li>
    </ul>
</nav>

<!-- MAIN CONTENT -->
<main class="containerListe">
    <?php if(!in_array("19", $prv) && !in_array("20", $prv) && !in_array("21", $prv)): ?>
        <div class="unauthorized">
            <img src="/importgames/images/divers/emoticon-sad.png" alt="emoticon-sad" />
            <h2>Autorisation refusée, veuillez contacter le « super administrateur » du site.</h2>
        </div>
    <?php elseif(isset($page)): ?>
    	<h3><i class="fa fa-list-ul"></i>Liste des administrateurs</h3>
        <?php if(in_array("20", $prv)) { ?>
            <h3><a href="/importgames/backoff/ajoutadmin"><i class="fa fa-plus"></i>Ajouter un administrateur</a></h3>
        <?php } ?>
        <form class="formLines" method="POST">
            <label for="lignesAdmin">Afficher par : </label>
            <select id="lignesAdmin" name="lignesAdmin">
                <?php if($nbrAdmins[0] <= 100) { ?>
                <option value="5">5</option>
                <?php }
                if($nbrAdmins[0] <= 250) { ?>
                <option value="10">10</option>
                <?php } ?>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                <?php if($nbrAdmins[0] > 100) { ?>
                <option value="250">250</option>
                <?php }
                if($nbrAdmins[0] > 250) { ?>
                <option value="500">500</option>
                <?php } ?>
            </select>
        </form>
        <div>Résultats <?= $resultDebut ?> à <?= htmlspecialchars($resultFin) ?> sur <?= htmlspecialchars($nbrAdmins[0]) ?></div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
                <?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/admins-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/admins-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($next)): ?>
                    <div class="pageSuiv"><a href="/importgames/backoff/admins-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/admins-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                <?php endif;
                // Si le nombre de pages de pages est supérieur à 1 (voir administrateurs.php ligne 132),
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php // on affiche le nombre de pages avec leurs liens
                    for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/admins-page-<?= $i ?>" id="lienPageTop<?= $i ?>"><?= $i ?></a></span>
                    <?php endfor;
                } ?>
            </div>
        <?php } ?>
        <div class="tableScroll">
            <table>
                <thead>
                    <tr>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triAdminId">
                                    <span>Id</span><i id="arrowDownAdminId" class="fa fa-long-arrow-down"></i><i id="arrowUpAdminId" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triAdminName">
                                    <span>Nom</span><i id="arrDwnAdmName" class="fa fa-long-arrow-down"></i><i id="arrUpAdmName" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triAdminPass">
                                    <span class="tableHeader">Mot de passe</span><span class="tblHeader300600" title ="Mot de passe">Mot de ...</span><i id="arrDwnAdmPass" class="fa fa-long-arrow-down"></i><i id="arrUpAdmPass" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triAdminPrv">
                                    <span class="tableHeader">Privilèges</span><span class="tblHeader300600" title ="Privilèges">Prv...</span><i id="arrDwnAdmPrv" class="fa fa-long-arrow-down"></i><i id="arrUpAdmPrv" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <th>
                            <form method="POST">
                                <button class="btnTri" type="submit" name="triAdminDateReg">
                                    <span class="tableHeader">Date d'inscription</span><span class="tblHeader300600" title ="Date d'inscription">Date i...</span><i id="arrDwnAdmReg" class="fa fa-long-arrow-down"></i><i id="arrUpAdmReg" class="fa fa-long-arrow-up"></i>
                                </button>
                            </form>
                        </th>
                        <?php if(in_array("21", $prv)) { ?>
                            <th>Options</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($admins as $admin): ?>
        	        <tr>
        	            <td><?= htmlspecialchars($admin["id"]) ?></td>
        	            <td>
                            <?php if($admin["name"]): echo htmlspecialchars($admin["name"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td title="<?= htmlspecialchars($admin["password"]) ?>">
                            <?php if($admin["password"]): echo htmlspecialchars(couperTexte($admin["password"])); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($admin["prv"]): echo htmlspecialchars($admin["prv"]); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if($admin["date_reg"]): echo htmlspecialchars(date("d/m/Y", strtotime($admin["date_reg"]))); else: ?>
                                <i>À attribuer</i>
                            <?php endif; ?>
                        </td>
                        <?php if(in_array("21", $prv)) { ?>
            	            <td>
                                <a href="/importgames/backoff/modifadmin-<?= htmlspecialchars($admin["id"]) ?>" class="btnModif"><?php if($admin["name"]): ?><i class="fa fa-pencil-square-o"></i>Modifier<?php else: ?><i class="fa fa-exchange"></i>Remplacer<?php endif; ?></a>
                                <?php if($admin["name"]) { ?>
                                    <form class="formReset" method="POST">
                                        <button type="submit" id="resetAdmin<?= htmlspecialchars($admin["id"]) ?>" class="btnReset" name="resetAdmin" value="<?= htmlspecialchars($admin["id"]) ?>"><i class="fa fa-trash-o"></i>Supprimer</button>
                                        <!-- Token de vérification, voir fichier bdd_connection.php ligne 19 -->
                                        <input type="hidden" name="formToken" value="<?= $token ?>" />
                                    </form>
                                <?php } ?>
                            </td>
                        <?php } ?>
        	        </tr>
        	        <?php endforeach; ?>
            	</tbody>
            </table>
        </div>
        <?php if(isset($navigation)) { ?>
            <div class="navigation">
            	<?php if(isset($prev) && isset($next)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/admins-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
                    <div class="pageSuiv"><a href="/importgames/backoff/admins-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
            	<?php elseif(isset($next)): ?>
                	<div class="pageSuiv"><a href="/importgames/backoff/admins-page-<?= $next ?>">Suivant <i class="fa fa-angle-double-right" aria-hidden="true"></i></a></div>
                <?php elseif(isset($prev)): ?>
                    <div class="pagePrec"><a href="/importgames/backoff/admins-page-<?= $prev ?>"><i class="fa fa-angle-double-left" aria-hidden="true"></i> Précédent</a></div>
            	<?php endif;
                if($nbrPages > 1) { ?>
                    <span>Pages : </span>
                    <?php for($i = 1 ; $i <= $nbrPages ; $i++): ?>
                        <span class="liensPages"><a href="/importgames/backoff/admins-page-<?= $i ?>" id="lienPage<?= $i ?>"><?= $i ?></a></span>	
            		<?php endfor;
                } ?>
            </div>
        <?php }
    endif; ?>
    <div class="backLink"><a href="/importgames/backoff/tableau-de-bord"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Accueil</a></div>
</main>

<!-- Token de session, voir fichier bdd_connection.php ligne 19 -->
<?php $_SESSION["token"] = htmlspecialchars($token); ?>